#include QMK_KEYBOARD_H

enum layers {
    _QWERTY = 0,
	_QWERTYSETTINGS,
    _WORKMAN,
    _NUMBERS,
    _SYMBOLS,
    _FUNCTION,
    _NAVIGATION,
    _SWAP,
    _SETTINGS
};

// Aliases for readability
#define WORKMAN             DF(_WORKMAN) //change default layer
#define QWERTY              DF(_QWERTY) //change default layer
//#define DVORAK            DF(_DVORAK)
//#define COLEMAK           DF(_COLEMAK_DH)

// #define NUMBERS             MO(_NUMBERS)
// #define SYMBOLS             MO(_SYMBOLS)
// #define FKEYS               MO(_FUNCTION)
// #define NAVKEYS             MO(_NAVIGATION)
// #define SETTING             MO(_SETTINGS)
// #define SWAP                MO(_SWAP)

// HOME ROW MODS - GUI ALT SHIFT CONTROL
#define HMOD_A              MT(MOD_LGUI, KC_A)
#define HMOD_S              MT(MOD_LALT, KC_S)
#define HMOD_H              MT(MOD_LSFT, KC_H)
#define HMOD_D              MT(MOD_LSFT, KC_D)
#define HMOD_T              MT(MOD_LCTL, KC_T)
#define HMOD_F              MT(MOD_LCTL, KC_F)
// HOME ROW MODS - CONTROL SHIFT ALT GUI
#define HMOD_N              MT(MOD_RCTL, KC_N)
#define HMOD_J              MT(MOD_RCTL, KC_J)
#define HMOD_E              MT(MOD_RSFT, KC_E)
#define HMOD_K              MT(MOD_RSFT, KC_K)
#define HMOD_O              MT(MOD_RALT, KC_O)
#define HMOD_L              MT(MOD_RALT, KC_L)
#define HMOD_I              MT(MOD_RGUI, KC_I)
#define HMOD_SEMICOLON      MT(MOD_RGUI, KC_SEMICOLON)

// UPPER THUMB MODS
#define UTMOD_LL            LT(_FUNCTION, KC_UNDERSCORE)
#define UTMOD_LR            LT(_SWAP, KC_MINUS)
#define UTMOD_RL            LT(_SWAP, KC_PLUS)
#define UTMOD_RR            LT(_FUNCTION, KC_EQUAL)

// LOWER THUMB MODS
#define TMOD_F13        	LT(_SETTINGS, KC_F13)
#define TMOD_LGUI           LT(_SYMBOLS, KC_LGUI)
#define TMOD_SPC            LT(_NUMBERS, KC_SPC)
#define TMOD_TAB            LT(_NAVIGATION, KC_TAB)

#define TMOD_ENT            LT(_NAVIGATION, KC_ENT)
#define TMOD_BSPCR          LT(_NUMBERS, KC_BSPC)
//#define TMOD_BSPC           LT(_NAVIGATION, KC_BSPC)
//#define TMOD_ENTR           LT(_NUMBERS, KC_ENT)

#define TMOD_LALT           LT(_SYMBOLS, KC_LALT)
#define TMOD_PRINTSCREEN    LT(_SETTINGS, KC_PRINT_SCREEN)


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_QWERTY] = LAYOUT_ortho_5x15(
		KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_INS, KC_HOME,
		KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_DEL, KC_END,
		KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_BSLS, KC_PSCR, KC_PGUP,
		KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_GRV, KC_RSFT, KC_UP, KC_PGDN,
		KC_LCTL, KC_LGUI, KC_LALT, KC_F13, KC_F14, KC_SPC, KC_TAB, LT(1,KC_APP), KC_ENT, KC_BSPC, KC_RALT, KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
	),
	[_QWERTYSETTINGS] = LAYOUT_ortho_5x15(
		KC_TRNS, QWERTY, KC_TRNS, KC_TRNS, WORKMAN, KC_TRNS, KC_TRNS, QK_BOOT, KC_TRNS, KC_TRNS, KC_PEQL, KC_PMNS, KC_PPLS, RGB_SPI, RGB_HUI,
		KC_MS_ACL1, KC_TRNS, KC_MS_UP, KC_TRNS, KC_MS_WHLU, KC_TRNS, KC_MS_BTN2, EE_CLR, KC_TRNS, KC_P7, KC_P8, KC_P9, KC_PAST, RGB_SPD, RGB_HUD,
		KC_MS_ACL0, KC_MS_LEFT, KC_MS_DOWN, KC_MS_RGHT, KC_MS_WHLD, KC_TRNS, KC_MS_BTN3, DB_TOGG, KC_TRNS, KC_P4, KC_P5, KC_P6, KC_PSLS, RGB_TOG, RGB_SAI,
		KC_MS_ACL2, KC_MS_LEFT, KC_TRNS, KC_MS_RGHT, KC_TRNS, KC_TRNS, KC_MS_BTN1, KC_TRNS, KC_P0, KC_P1, KC_P2, KC_P3, KC_TRNS, RGB_VAI, RGB_SAD,
		KC_TRNS, GU_TOGG, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PENT, KC_BSPC, KC_PDOT, KC_TRNS, RGB_RMOD, RGB_VAD, RGB_MOD
	),
	[_WORKMAN] = LAYOUT_ortho_5x15(
		KC_ESC, KC_Q, KC_D, KC_R, KC_W, KC_B, KC_NO, KC_NO, KC_NO, KC_J, KC_F, KC_U, KC_P, KC_SCLN, KC_BSLS,
		LSFT(KC_CAPS), HMOD_A, HMOD_S, HMOD_H, HMOD_T, KC_G, KC_NO, KC_NO, KC_NO, KC_Y, HMOD_N, HMOD_E, HMOD_O, HMOD_I, RSFT_T(KC_QUOT),
		LCTL_T(KC_INS), KC_Z, KC_X, KC_M, KC_C, KC_V, KC_NO, KC_NO, KC_NO, KC_K, KC_L, KC_COMM, KC_DOT, KC_SLSH, RCTL_T(KC_DEL),
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, UTMOD_LL, UTMOD_LR, KC_NO, UTMOD_RL, UTMOD_RR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_VOLU, KC_VOLD, KC_MPLY, TMOD_F13, TMOD_LGUI, TMOD_SPC, TMOD_TAB, LT(1,KC_APP), TMOD_ENT, TMOD_BSPCR, TMOD_LALT, TMOD_PRINTSCREEN, KC_FIND, KC_PGUP, KC_PGDN
	),
	[_NUMBERS] = LAYOUT_ortho_5x15(
		KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_NO, KC_NO, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_4, KC_5, KC_6, KC_PMNS, KC_PPLS,
		KC_TRNS, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, KC_NO, KC_0, KC_1, KC_2, KC_3, KC_PSLS, KC_PAST,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
	),
	[_SYMBOLS] = LAYOUT_ortho_5x15(
		KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_NO, KC_NO, KC_NO, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_PIPE,
		KC_TRNS, KC_UNDS, KC_MINS, KC_PLUS, KC_EQL, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_LBRC, KC_RBRC, KC_LCBR, KC_RCBR, KC_DQUO,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_LT, KC_GT, KC_TRNS,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
	),
	[_NAVIGATION] = LAYOUT_ortho_5x15(
		KC_TRNS, KC_ACL1, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_MS_BTN1, KC_MS_BTN3, KC_MS_BTN2, KC_MS_BTN4, KC_MS_BTN5,
		KC_TRNS, KC_ACL0, KC_MS_LEFT, KC_MS_UP, KC_MS_RGHT, KC_MS_WH_UP, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_ACL2, KC_MS_WH_LEFT, KC_MS_DOWN, KC_MS_WH_RIGHT, KC_MS_WH_DOWN, KC_NO, KC_NO, KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_INS, KC_DEL,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
	),
	[_FUNCTION] = LAYOUT_ortho_5x15(
		KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_NO, KC_NO, KC_NO, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12,
		KC_BRIU, KC_MPRV, KC_MPLY, KC_MUTE, KC_MNXT, KC_VOLU, KC_NO, KC_NO, KC_NO, KC_WBAK, KC_WSCH, KC_WHOM, KC_WFWD, KC_WFAV, KC_WREF,
		KC_BRID, KC_MRWD, KC_MSTP, KC_EJCT, KC_MFFD, KC_VOLD, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MYCM, KC_CALC,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
	),
	[_SWAP] = LAYOUT_ortho_5x15(
		KC_TRNS, QWERTY, KC_TRNS, KC_TRNS, WORKMAN, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
	),
	[_SETTINGS] = LAYOUT_ortho_5x15(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, QK_REBOOT, GE_SWAP, BS_SWAP, AG_SWAP, GU_OFF, NK_OFF,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, DB_TOGG, GE_NORM, BS_NORM, AG_NORM, GU_ON, NK_ON,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, EE_CLR, KC_CAPS, KC_NUM, KC_SCRL, GU_TOGG, NK_TOGG,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
	)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
